/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type InEuint64Struct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEuint64StructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export interface GhostVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deposit"
      | "getBalance"
      | "getLastRuleAbove"
      | "getRuleThreshold"
      | "getTradeIntent"
      | "grantBalanceViewer"
      | "publishBalance"
      | "refreshRuleCheck"
      | "setRuleThreshold"
      | "setTradeIntent"
      | "transferPrivate"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deposit",
    values: [InEuint64Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLastRuleAbove",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRuleThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTradeIntent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantBalanceViewer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "publishBalance",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "refreshRuleCheck",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setRuleThreshold",
    values: [InEuint64Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "setTradeIntent",
    values: [InEuint64Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "transferPrivate",
    values: [AddressLike, InEuint64Struct]
  ): string;

  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLastRuleAbove",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRuleThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTradeIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantBalanceViewer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publishBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refreshRuleCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRuleThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTradeIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferPrivate",
    data: BytesLike
  ): Result;
}

export interface GhostVault extends BaseContract {
  connect(runner?: ContractRunner | null): GhostVault;
  waitForDeployment(): Promise<this>;

  interface: GhostVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deposit: TypedContractMethod<
    [encryptedAmount: InEuint64Struct],
    [void],
    "nonpayable"
  >;

  getBalance: TypedContractMethod<[], [string], "view">;

  getLastRuleAbove: TypedContractMethod<[], [string], "view">;

  getRuleThreshold: TypedContractMethod<[], [string], "view">;

  getTradeIntent: TypedContractMethod<[], [string], "view">;

  grantBalanceViewer: TypedContractMethod<
    [viewer: AddressLike],
    [void],
    "nonpayable"
  >;

  publishBalance: TypedContractMethod<
    [ctHash: BytesLike, plaintext: BigNumberish, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  refreshRuleCheck: TypedContractMethod<[], [string], "nonpayable">;

  setRuleThreshold: TypedContractMethod<
    [encryptedThreshold: InEuint64Struct],
    [void],
    "nonpayable"
  >;

  setTradeIntent: TypedContractMethod<
    [encryptedAmount: InEuint64Struct],
    [void],
    "nonpayable"
  >;

  transferPrivate: TypedContractMethod<
    [to: AddressLike, encryptedAmount: InEuint64Struct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [encryptedAmount: InEuint64Struct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getLastRuleAbove"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRuleThreshold"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTradeIntent"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "grantBalanceViewer"
  ): TypedContractMethod<[viewer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "publishBalance"
  ): TypedContractMethod<
    [ctHash: BytesLike, plaintext: BigNumberish, signature: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "refreshRuleCheck"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "setRuleThreshold"
  ): TypedContractMethod<
    [encryptedThreshold: InEuint64Struct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTradeIntent"
  ): TypedContractMethod<
    [encryptedAmount: InEuint64Struct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferPrivate"
  ): TypedContractMethod<
    [to: AddressLike, encryptedAmount: InEuint64Struct],
    [void],
    "nonpayable"
  >;

  filters: {};
}
